### ISSUE TITLE
Run mass experiment with W&B

### ISSUE THREAD

**Issue by sangttruong** [sangttruong/nonmyopia#31]
Budget calculation:
12min / experiment / agent / 1CPU / 
in total: 30000 experiments
--> 6000h computing

CPU LIMIT:
80CPU/Turing      // mercury has 96, // 128 cpu skampere 
--> 90 =     // total number of cpus
--> maximum  90*0.6 = 60 agents/turing   // only use 60% of CPU
--> for skampere: limit is 0.6*128 = 75

GPU LIMIT:
one Experiment needs 5GB
--> 10GPU, each 12GB Turing
--> Maximum 2 exp. / GPU
--> Maximum 2*10 = 20 agents/turing

--> 10 GPU, each 16GB mercury
--> maximum 3 exp./GPU
--> maximum 10*3 = 30 agents/mercury

--> 8 GPU, each 80 GB skampere
--> maximum 16 exp/GPU
--> maximum 8*16 = 128 agents/skampere

OVERALL agents/Turing:
min (max(GPU_Limit), max(CPU_Limit) --> 20 agents/turing

machines:
4 * 20 = 80 agents   // 4 turing machines
2 * 30 = 60 agents   // 2 mercury machines
1 * 75 = 75 agents   // 1 skampere

Total time:
6000h / 215 agents = ~ 28 hours

**Comment by sangttruong** [comment]
Current roadblock: redesign visualization for massive experiments

**Comment by martinakaduc** [comment]
> Current roadblock: redesign visualization for massive experiments

Why is it the roadblock? Can you explain more? I thought we will run experiment, then run metric computing then visualize results.

**Comment by sangttruong** [comment]
the current ways of visualization produce too many plots, and we cannot include all of them in the paper. hence, we need better way of visualize the result

**Comment by martinakaduc** [comment]
**Note on How to Draw Plots:**

We will create 8 plots (2 noise levels × 4 cost functions) in the same image for each metric.

We have 2 metrics: final cumulative regret and the number of iterations required to achieve 90% of the final regret.

For each plot, we will include:

- 1 noise level
- Both discretized and non-discretized cases
- 1 cost function
- Each method will be represented by a point with standard deviation.
