### ISSUE TITLE
Implement reward model for different acqfs

### ISSUE THREAD

**Issue by martinakaduc** [sangttruong/nonmyopia#39]
We edit this file: https://github.com/sangttruong/nonmyopia/blob/master/sequence_design/acqf.py

**Comment by sangttruong** [comment]
is this just the matter of calling botorch acquisition functions or do we have to re-implement the acquisition functions by ourselves?

**Comment by martinakaduc** [comment]
> is this just the matter of calling botorch acquisition functions or do we have to re-implement the acquisition functions by ourselves?

For the botorch acqfs, we only need to create an inherited reward model instance for it. See https://github.com/sangttruong/nonmyopia/blob/680fc3d813417ec92df651c2c3fc0f19916c62b6/sequence_design/acqf.py#L69

For HES, we might need to implement ourself based on which has been implemented in synthetic settings.

**Comment by sangttruong** [comment]
Couldn't you copy the material from here? https://github.com/sangttruong/nonmyopia/blob/master/sequence_design/actor.py#L40

**Comment by martinakaduc** [comment]
> Couldn't you copy the material from here? https://github.com/sangttruong/nonmyopia/blob/master/sequence_design/actor.py#L40

Yes, I think it similar. Copying is quick. The main process that takes time is testing and ensuring it runs smoothly.
