### ISSUE TITLE
Anonymizing code

### ISSUE THREAD

**Issue by martinakaduc** [sangttruong/nonmyopia#67]
This issue contains cleaning up hard-coded path and related private stuffs

**Comment by sangttruong** [comment]
@martinakaduc Will we need to merge the branch corresponding to this issue to `main`?

**Comment by martinakaduc** [comment]
I think this branch is almost the same as the main branch but with all private information anonymized. We can close this issue and keep the branch until review period ends. After that, we can delete the anonymized branch.
